# tractive -c "mailarchive.config.yaml" --filter --column-name "component" --operator "LIKE" --column-value "MailArchive:%" -M

trac:
  database: sqlite://../../trac-svn-db/trac/ietfdb/db/trac.db

github:
  repo: "ietf-svn-conversion/mailarch-final"

revmap_path: ./svn-git-maps/mailarch-revmap.txt

milestones:
  Cleanup:
    :name: Cleanup
    :due: 0
    :completed: 0
    :description: ''
  '2.02':
    :name: '2.02'
    :due: 1183327200000000
    :completed: 1183413805000000
    :description: |-
      [query:status=new|assigned|reopened&milestone=2.02&order=priority Open Tickets]:
        [[TicketQuery(status=new|assigned|reopened&milestone=2.02&order=priority)]]

      [[MilestoneTickets(milestone:2.02)]]
  '2.03':
    :name: '2.03'
    :due: 1183932000000000
    :completed: 1184083819000000
    :description: |-
      [query:status=new|assigned|reopened&milestone=2.03&order=priority Open Tickets]:
        [[TicketQuery(status=new|assigned|reopened&milestone=2.03&order=priority)]]

      [[MilestoneTickets(milestone:2.03)]]
  Soonish:
    :name: Soonish
    :due: 1214863200000000
    :completed: 1214863200000000
    :description: ''
  '2.04':
    :name: '2.04'
    :due: 1184536800000000
    :completed: 1184617555000000
    :description: |-
      [query:status=new|assigned|reopened&milestone=2.03&order=priority Open Tickets]:
        [[TicketQuery(status=new|assigned|reopened&milestone=2.04&order=priority)]]

      [[MilestoneTickets(milestone:2.04)]]
  '2.05':
    :name: '2.05'
    :due: 1186351200000000
    :completed: 1193816257000000
    :description: |-
      [query:status=new|assigned|reopened&milestone=2.03&order=priority Open Tickets]:
        [[TicketQuery(status=new|assigned|reopened&milestone=2.05&order=priority)]]

      [[MilestoneTickets(milestone:2.05)]]
  Database Schema Conversion:
    :name: Database Schema Conversion
    :due: 0
    :completed: 1394028718000000
    :description: ''
  Draft Submission Tool:
    :name: Draft Submission Tool
    :due: 0
    :completed: 1394028719000000
    :description: "[query:status=new|assigned|reopened&milestone=Submission+Tool&order=priority
      Open Tickets]:\r\n  [[TicketQuery(status=new|assigned|reopened&milestone=Submission+Tool&order=priority)]]\r\n\r\n[[MilestoneTickets(milestone:Draft
      Submission Tool)]]"
  Philly Sprint:
    :name: Philly Sprint
    :due: 0
    :completed: 1204963200000000
    :description: ''
  2.12 - Vancouver Sprint:
    :name: 2.12 - Vancouver Sprint
    :due: 0
    :completed: 1196496000000000
    :description: ''
  '2.06':
    :name: '2.06'
    :due: 1194217200000000
    :completed: 1194278106000000
    :description: |-
      [query:status=new|assigned|reopened&milestone=2.03&order=priority Open Tickets]:
        [[TicketQuery(status=new|assigned|reopened&milestone=2.06&order=priority)]]

      [[MilestoneTickets(milestone:2.06)]]
  '2.07':
    :name: '2.07'
    :due: 1209279600000000
    :completed: 1211094000000000
    :description: |-
      This milestone does not have any specific targeted issues, but covers the various
      code committed on the 2.00 branch since [milestone:2.06 Milestone 2.06] -- see
      log:branch/2.00@969:HEAD

      [query:status=new|assigned|reopened&milestone=2.07&order=priority Open Tickets]:
        [[TicketQuery(status=new|assigned|reopened&milestone=2.07&order=priority)]]

      [[MilestoneTickets(milestone:2.07)]]
  '2.08':
    :name: '2.08'
    :due: 1210489200000000
    :completed: 1224658800000000
    :description: |-
      [query:status=new|assigned|reopened&milestone=2.08&order=priority Open Tickets]:
        [[TicketQuery(status=new|assigned|reopened&milestone=2.08&order=priority)]]

      [[MilestoneTickets(milestone:2.08)]]
  '3.01':
    :name: '3.01'
    :due: 0
    :completed: 1279644120000000
    :description: ''
  '3.02':
    :name: '3.02'
    :due: 1279749600000000
    :completed: 1279749600000000
    :description: ''
  '3.05':
    :name: '3.05'
    :due: 1282600800000000
    :completed: 1282656711000000
    :description: |-
      [query:status=new|assigned|reopened&milestone=Submission+Tool&order=priority Open Tickets]:
        [[TicketQuery(status=new|assigned|reopened&milestone=3.05&order=priority)]]

      [[MilestoneTickets(milestone:3.05)]]
  '3.06':
    :name: '3.06'
    :due: 0
    :completed: 1284977460000000
    :description: ''
  '3.09':
    :name: '3.09'
    :due: 1289084400000000
    :completed: 1289296537000000
    :description: ''
  '3.10':
    :name: '3.10'
    :due: 0
    :completed: 1291754357000000
    :description: "\n  * Fix css for IPR header (status column was included by mistake).
      \ Fixes \n    issue #546.\n\n  * Tweak some GUI strings in the Liaison Manager\n\n
      \ From adam@nostrum.com: \n\n  * Added week-at-a-time view to agenda page when
      viewing selected areas \n    and/or groups. If no groups are selected, the week
      view is hidden, leaving the\n    base-level functionality unchanged. \n\n  From
      peter.musgrave@magorcorp.com: \n\n  * 548# Link in IPR column should use an
      absolute, not relative URL.  This \n    fixes issue #546.\n\n  From kivinen@iki.fi:
      \n\n  * Added new setting to the /cookies page which enables always showing\n
      \   full document text instead of showing beginning of the document. This \n
      \   fixes issue #551.\n\n  From rjsparks@nostrum.com: \n\n  * Refined the email
      sent when an position changes.\n"
  WG Chairs Tracker:
    :name: WG Chairs Tracker
    :due: 0
    :completed: 0
    :description: ''
  Alternate Streams Support:
    :name: Alternate Streams Support
    :due: 0
    :completed: 0
    :description: ''
  RFC/IANA State Support:
    :name: RFC/IANA State Support
    :due: 0
    :completed: 1394028720000000
    :description: ''
  WG Charters Toolo:
    :name: WG Charters Toolo
    :due: 0
    :completed: 1394028722000000
    :description: ''
  Community Support:
    :name: Community Support
    :due: 0
    :completed: 1394028716000000
    :description: ''
  '4.00':
    :name: '4.00'
    :due: 1330167600000000
    :completed: 1332581623000000
    :description: "Major Release: Transition to new database schema\r\n\r\n[[TicketStats(
      height=250,daterange=4w,res_days=1,query=version='4.00'&type='defect'&milestone='')]]\r\n\r\n[query:status=new|assigned|reopened&version=4.00&type=defect&milestone=&order=priority
      Open Defect Tickets]:\r\n  [[TicketQuery(status=new|assigned|reopened&version=4.00&type=defect&milestone=&order=priority)]]\r\n\r\n[[MilestoneTickets(version:4.00;type:defect;milestone:)]]"
  '4.01':
    :name: '4.01'
    :due: 1330956000000000
    :completed: 1394028697000000
    :description: ''
  Agenda-1:
    :name: Agenda-1
    :due: 1353020400000000
    :completed: 1394028699000000
    :description: ''
  Agenda-2:
    :name: Agenda-2
    :due: 1354834800000000
    :completed: 1394028700000000
    :description: ''
  Agenda-3:
    :name: Agenda-3
    :due: 1367013600000000
    :completed: 1394028702000000
    :description: ''
  Agenda-IETF-86:
    :name: Agenda-IETF-86
    :due: 1363302000000000
    :completed: 1394028701000000
    :description: ''
  Agenda-IETF-87:
    :name: Agenda-IETF-87
    :due: 1374962400000000
    :completed: 1394028708000000
    :description: ''
  Agenda-4:
    :name: Agenda-4
    :due: 1370120400000000
    :completed: 1394028704000000
    :description: ''
  Agenda-5:
    :name: Agenda-5
    :due: 1372712400000000
    :completed: 1394028706000000
    :description: ''
  Agenda-6:
    :name: Agenda-6
    :due: 1375390800000000
    :completed: 1394028710000000
    :description: ''
  Agenda - manual placement:
    :name: Agenda - manual placement
    :due: 0
    :completed: 1389996392000000
    :description: ''
  Agenda - automatic placement:
    :name: Agenda - automatic placement
    :due: 0
    :completed: 1394028712000000
    :description: ''
  Agenda - javascript testing:
    :name: Agenda - javascript testing
    :due: 0
    :completed: 0
    :description: ''
  Agenda - future:
    :name: Agenda - future
    :due: 0
    :completed: 0
    :description: ''
  5.y.y:
    :name: 5.y.y
    :due: 0
    :completed: 1428660000000000
    :description: ''
  'Maintenance: IRTF Groups':
    :name: 'Maintenance: IRTF Groups'
    :due: 0
    :completed: 0
    :description: ''
  'Maintenance: Team Pages':
    :name: 'Maintenance: Team Pages'
    :due: 0
    :completed: 0
    :description: ''
  'Maintenance: Performance':
    :name: 'Maintenance: Performance'
    :due: 0
    :completed: 0
    :description: ''
  'Maintenance: Charters':
    :name: 'Maintenance: Charters'
    :due: 0
    :completed: 0
    :description: ''
  'Maintenance: Choosing People':
    :name: 'Maintenance: Choosing People'
    :due: 0
    :completed: 0
    :description: ''
  6.x.x:
    :name: 6.x.x
    :due: 0
    :completed: 0
    :description: ''
labels:
  type:
    task: type_task
    defect: type_defect
    cleanup: type_cleanup
    enhancement: type_enhancement
  resolution:
    fixed: resolution_fixed
    wontfix: resolution_wontfix
    duplicate: resolution_duplicate
    invalid: resolution_invalid
    overtaken by events: resolution_overtaken by events
    worksforme: resolution_worksforme
    cannot reproduce: resolution_cannot reproduce
    deployed: resolution_deployed
  keywords:
    IPR_Tool: keyword_IPR_Tool
    diff: keyword_diff
    images: keyword_images
    ssl: keyword_ssl
    sprint: keyword_sprint
    easy: keyword_easy
    imported: keyword_imported
    survey: keyword_survey
    tool: keyword_tool
    Multiple_From_header_exploit: keyword_Multiple_From_header_exploit
    datatracker_email_informational: keyword_datatracker_email_informational
    sprint_agenda: keyword_sprint_agenda
    big_project: keyword_big_project
    cleanup: keyword_cleanup
    resnick: keyword_resnick
    hard: keyword_hard
    bof: keyword_bof
    drafts: keyword_drafts
    filter_ui: keyword_filter_ui
    meeting_session_request: keyword_meeting_session_request
    wg_adoption: keyword_wg_adoption
    materials: keyword_materials
    shepherd: keyword_shepherd
    Search: keyword_Search
    Group: keyword_Group
    Filter: keyword_Filter
    message_missing: keyword_message_missing
    advanced_search: keyword_advanced_search
    tags: keyword_tags
    check-box: keyword_check-box
    documentation: keyword_documentation
    submit: keyword_submit
    state: keyword_state
    tag: keyword_tag
    next: keyword_next
    HTML: keyword_HTML
    sign_out: keyword_sign_out
    plenary_agenda: keyword_plenary_agenda
    big: keyword_big
    Cross_Area_Management: keyword_Cross_Area_Management
    Concluded_WGs: keyword_Concluded_WGs
    Wrap_Shepherd: keyword_Wrap_Shepherd
    sreq: keyword_sreq
    6lo: keyword_6lo
    Page_count_telechat: keyword_Page_count_telechat
    Short_summaries_for_WG: keyword_Short_summaries_for_WG
    Draft_approval: keyword_Draft_approval
    Bad_data: keyword_Bad_data
    address_change_check: keyword_address_change_check
    accessabillity: keyword_accessabillity
    markdown: keyword_markdown
    liaison: keyword_liaison
    IESG_agenda_overlay: keyword_IESG_agenda_overlay
    search: keyword_search
    replaced-by: keyword_replaced-by
    codestand: keyword_codestand
    ui: keyword_ui
    presentation_file_renaming: keyword_presentation_file_renaming
    person: keyword_person
    html_santitize_css_style: keyword_html_santitize_css_style
    NOTEWELL: keyword_NOTEWELL
    rfc-xmldiff: keyword_rfc-xmldiff
    newcomers: keyword_newcomers
    mentoring_program: keyword_mentoring_program
    EDU: keyword_EDU
    yang: keyword_yang
    3rd_party: keyword_3rd_party
    ISE: keyword_ISE
    stream: keyword_stream
    chartering: keyword_chartering
    proceedings: keyword_proceedings
    cron_output: keyword_cron_output
    stats: keyword_stats
    filename_ASCII: keyword_filename_ASCII
    IRTF: keyword_IRTF
    json_api: keyword_json_api
    webex: keyword_webex
    meetings_agenda: keyword_meetings_agenda
    timezone: keyword_timezone
    iterim_meeting: keyword_iterim_meeting
    filestorage: keyword_filestorage
    YANG: keyword_YANG
    regression: keyword_regression
    bibxml_xml2rfc: keyword_bibxml_xml2rfc
    login_error: keyword_login_error
    agenda_materials: keyword_agenda_materials
    draft-upload: keyword_draft-upload
    xml: keyword_xml
    references: keyword_references
    expertise: keyword_expertise
    Account_Recovery: keyword_Account_Recovery
    Restoration: keyword_Restoration
  component:
    admin/:
      name: 'component: admin/'
      color: 00000f
    doc/:
      name: 'component: doc/'
      color: 00000f
    ipr/:
      name: 'component: ipr/'
      color: 00000f
    'Datatracker: Base templates':
      name: 'component: Datatracker: Base templates'
      color: 00000f
    idtracker/:
      name: 'component: idtracker/'
      color: 00000f
    submit/:
      name: 'component: submit/'
      color: 00000f
    list/:
      name: 'component: list/'
      color: 00000f
    'Datatracker: Infrastructure':
      name: 'component: Datatracker: Infrastructure'
      color: 00000f
    "-- Other":
      name: 'component: -- Other'
      color: 00000f
    'Datatracker: Testing':
      name: 'component: Datatracker: Testing'
      color: 00000f
    'Datatracker: Redirects':
      name: 'component: Datatracker: Redirects'
      color: 00000f
    drafts/:
      name: 'component: drafts/'
      color: 00000f
    meeting/:
      name: 'component: meeting/'
      color: 00000f
    feed/:
      name: 'component: feed/'
      color: 00000f
    ann/:
      name: 'component: ann/'
      color: 00000f
    liaison/:
      name: 'component: liaison/'
      color: 00000f
    'Project: Liaison Management':
      name: 'component: Project: Liaison Management'
      color: 00000f
    'Datatracker: Email sending':
      name: 'component: Datatracker: Email sending'
      color: 00000f
    ietfauth/:
      name: 'component: ietfauth/'
      color: 00000f
    wg/:
      name: 'component: wg/'
      color: 00000f
    iesg/:
      name: 'component: iesg/'
      color: 00000f
    datatracker.ietf.org:
      name: 'component: datatracker.ietf.org'
      color: 00000f
    Other ==:
      name: 'component: Other =='
      color: 00000f
    doc/ ==:
      name: 'component: doc/ =='
      color: 00000f
    wgtracker:
      name: 'component: wgtracker'
      color: 00000f
    notify:
      name: 'component: notify'
      color: 00000f
    wgcharter:
      name: 'component: wgcharter'
      color: 00000f
    community/:
      name: 'component: community/'
      color: 00000f
    doc/charter-:
      name: 'component: doc/charter-'
      color: 00000f
    doc/draft-:
      name: 'component: doc/draft-'
      color: 00000f
    'Project: Agenda':
      name: 'component: Project: Agenda'
      color: 00000f
    Nomcom:
      name: 'component: Nomcom'
      color: 00000f
    secr/sreq/:
      name: 'component: secr/sreq/'
      color: 00000f
    secr/:
      name: 'component: secr/'
      color: 00000f
    nomcom/:
      name: 'component: nomcom/'
      color: 00000f
    group/:
      name: 'component: group/'
      color: 00000f
    statesync:
      name: 'component: statesync'
      color: 00000f
    meeting/*/schedule/:
      name: 'component: meeting/*/schedule/'
      color: 00000f
    'Project: IPR Tool':
      name: 'component: Project: IPR Tool'
      color: 00000f
    person/:
      name: 'component: person/'
      color: 00000f
    sync/:
      name: 'component: sync/'
      color: 00000f
    mailtrigger/:
      name: 'component: mailtrigger/'
      color: 00000f
    accounts/:
      name: 'component: accounts/'
      color: 00000f
    review/:
      name: 'component: review/'
      color: 00000f
    'Datatracker: Yang':
      name: 'component: Datatracker: Yang'
      color: 00000f
    stats/:
      name: 'component: stats/'
      color: 00000f
    'Project: GDPR Compliance':
      name: 'component: Project: GDPR Compliance'
      color: 00000f
    api/:
      name: 'component: api/'
      color: 00000f
  severity: {}
  priority:
    major:
      name: major
      color: 22dd00
    minor:
      name: minor
      color: ee00aa
    blocker:
      name: blocker
      color:
    medium:
      name: medium
      color:
    trivial:
      name: trivial
      color: 22dd00
    critical:
      name: critical
      color: aadd88
  tracstate:
    accepted:
      name: accepted
      color: 22dd00
    archived:
      name: archived
      color: aadd88
    assigned:
      name: assigned
      color: ee00aa
    close:
      name: close
      color: 22dd00
    closed:
      name: closed
      color: aadd88
    deployed:
      name: deployed
      color: ee00aa
    new:
      name: new
      color: 22dd00
    reopened:
      name: reopened
      color: aadd88
    under_review:
      name: under_review
      color: ee00aa
    waiting:
      name: waiting
      color:

ticket:
  attachments:
    url: https://raw.githubusercontent.com/ietf-tools/svntrac-converted-attachments/main/ietfdb/attachments/ticket
    hashed: true

wiki:
  attachments:
    url: https://raw.githubusercontent.com/ietf-tools/svntrac-converted-attachments/main/ietfdb/attachments/wiki
    hashed: true
