# tractive -c "xml2rfc.config.yaml" --filter --column-name "component" --operator "!=" --column-value "v3 vocabulary" -M

trac:
  database: sqlite://../../trac-svn-db/trac/xml2rfc/db/trac.db

github:
  token: "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"
  repo: "ietf-svn-conversion/xml2rfc-final"

# need to fix in readme. (not under github)
revmap_path: ../../svn-git-maps/xml2rfc-revmap.txt
# revmap_path: ./foobar-revmap.txt

users:
  julian.reschke@gmx.de:
    email: julian.reschke@gmx.de
    name:
    username: hassanakbar
  adam@nostrum.com:
    email: adam@nostrum.com
    name:
    username: hassanakbar
  tom111.taylor@bell.net:
    email: tom111.taylor@bell.net
    name:
    username: ronaldtse
  spencer@wonderhamster.org:
    email: spencer@wonderhamster.org
    name:
    username:
  chris.dearlove@baesystems.com:
    email: chris.dearlove@baesystems.com
    name:
    username:
  lars.eggert@nokia.com:
    email: lars.eggert@nokia.com
    name:
    username:
  tony@att.com:
    email: tony@att.com
    name:
    username: ronaldtse
  elwynd@dial.pipex.com:
    email: elwynd@dial.pipex.com
    name:
    username:
  ahagens@amsl.com:
    email: ahagens@amsl.com
    name:
    username:
  miek@miek.nl:
    email: miek@miek.nl
    name:
    username:
  arusso@amsl.com:
    email: arusso@amsl.com
    name:
    username:
  henrik@levkowetz.com:
    email: henrik@levkowetz.com
    name:
    username:
  rjsparks@nostrum.com:
    email: rjsparks@nostrum.com
    name:
    username:
  tterriberry@mozilla.com:
    email: tterriberry@mozilla.com
    name:
    username:
  bob.hinden@gmail.com:
    email: bob.hinden@gmail.com
    name:
    username: ronaldtse
  randy@psg.com:
    email: randy@psg.com
    name:
    username:
  johnl@iecc.com:
    email: johnl@iecc.com
    name:
    username:
  bortzmeyer+ietf@nic.fr:
    email: bortzmeyer+ietf@nic.fr
    name:
    username:
  donald.coffin@reminetworks.com:
    email: donald.coffin@reminetworks.com
    name:
    username:
  jonathan@vidyo.com:
    email: jonathan@vidyo.com
    name:
    username: ronaldtse
  cabo@tzi.org:
    email: cabo@tzi.org
    name:
    username: hassanakbar
  infrastation@yandex.ru:
    email: infrastation@yandex.ru
    name:
    username:
  kerlyn@ieee.org:
    email: kerlyn@ieee.org
    name:
    username:
  ietf@augustcellars.com:
    email: ietf@augustcellars.com
    name:
    username:
  magnus.westerlund@ericsson.com:
    email: magnus.westerlund@ericsson.com
    name:
    username:
  brian.e.carpenter@gmail.com:
    email: brian.e.carpenter@gmail.com
    name:
    username:
  kivinen@iki.fi:
    email: kivinen@iki.fi
    name:
    username:
  ibc@aliax.net:
    email: ibc@aliax.net
    name:
    username: hassanakbar
  jgs@juniper.net:
    email: jgs@juniper.net
    name:
    username:
  ht@inf.ed.ac.uk:
    email: ht@inf.ed.ac.uk
    name:
    username:
  fred@cisco.com:
    email: fred@cisco.com
    name:
    username:
  yaakov_s@rad.com:
    email: yaakov_s@rad.com
    name:
    username:
  john-ietf@jck.com:
    email: john-ietf@jck.com
    name:
    username:
  jsalowey@cisco.com:
    email: jsalowey@cisco.com
    name:
    username:
  tomasz.mrugalski@gmail.com:
    email: tomasz.mrugalski@gmail.com
    name:
    username: hassanakbar
  mcr@sandelman.ca:
    email: mcr@sandelman.ca
    name:
    username:
  l.wood@surrey.ac.uk:
    email: l.wood@surrey.ac.uk
    name:
    username:
  william.atwood@concordia.ca:
    email: william.atwood@concordia.ca
    name:
    username: ronaldtse
  dreibh@iem.uni-due.de:
    email: dreibh@iem.uni-due.de
    name:
    username:
  schmidt@informatik.haw-hamburg.de:
    email: schmidt@informatik.haw-hamburg.de
    name:
    username:
  bob.briscoe@bt.com:
    email: bob.briscoe@bt.com
    name:
    username:
  mnot@pobox.com:
    email: mnot@pobox.com
    name:
    username:
  tbray@textuality.com:
    email: tbray@textuality.com
    name:
    username:
  ian@iay.org.uk:
    email: ian@iay.org.uk
    name:
    username:
  n.brownlee@auckland.ac.nz:
    email: n.brownlee@auckland.ac.nz
    name:
    username:
  paitken@cisco.com:
    email: paitken@cisco.com
    name:
    username:
  dev+ietf@seantek.com:
    email: dev+ietf@seantek.com
    name:
    username:
  michael.jones@microsoft.com:
    email: michael.jones@microsoft.com
    name:
    username:
  mferguson@amsl.com:
    email: mferguson@amsl.com
    name:
    username:
  tore@redpill-linpro.com:
    email: tore@redpill-linpro.com
    name:
    username:
  srdonovan@usdonovans.com:
    email: srdonovan@usdonovans.com
    name:
    username:
  ott@mirix.org:
    email: ott@mirix.org
    name:
    username:
  bo.burman@ericsson.com:
    email: bo.burman@ericsson.com
    name:
    username:
  rhansen@bbn.com:
    email: rhansen@bbn.com
    name:
    username:
  martin.thomson@gmail.com:
    email: martin.thomson@gmail.com
    name:
    username:
  erik.wilde@dret.net:
    email: erik.wilde@dret.net
    name:
    username:
  kwatsen@juniper.net:
    email: kwatsen@juniper.net
    name:
    username:
  worley@ariadne.com:
    email: worley@ariadne.com
    name:
    username:
  lars@netapp.com:
    email: lars@netapp.com
    name:
    username:
  hlflanagan@gmail.com:
    email: hlflanagan@gmail.com
    name:
    username:
  dhruv.ietf@gmail.com:
    email: dhruv.ietf@gmail.com
    name:
    username:
  tale@dd.org:
    email: tale@dd.org
    name:
    username:
  jordi.palet@consulintel.es:
    email: jordi.palet@consulintel.es
    name:
    username:
  jyasskin@chromium.org:
    email: jyasskin@chromium.org
    name:
    username:
  scott@kitterman.com:
    email: scott@kitterman.com
    name:
    username:
  spf2@kitterman.com:
    email: spf2@kitterman.com
    name:
    username:
  tte@cs.fau.de:
    email: tte@cs.fau.de
    name:
    username:
  pusateri@bangj.com:
    email: pusateri@bangj.com
    name:
    username:
  shollenbeck@verisign.com:
    email: shollenbeck@verisign.com
    name:
    username:
  warren@kumari.net:
    email: warren@kumari.net
    name:
    username:
  paf@frobbit.se:
    email: paf@frobbit.se
    name:
    username:
  tom@erg.abdn.ac.uk:
    email: tom@erg.abdn.ac.uk
    name:
    username:
  daveoran@orandom.net:
    email: daveoran@orandom.net
    name:
    username:
  sginoza@amsl.com:
    email: sginoza@amsl.com
    name:
    username:
  mahoney@nostrum.com:
    email: mahoney@nostrum.com
    name:
    username:
  jmahoney@amsl.com:
    email: jmahoney@amsl.com
    name:
    username:
  lbartholomew@amsl.com:
    email: lbartholomew@amsl.com
    name:
    username:
  pravb@microsoft.com:
    email: pravb@microsoft.com
    name:
    username:
  rvanrheenen@amsl.com:
    email: rvanrheenen@amsl.com
    name:
    username:
  gregimirsky@gmail.com:
    email: gregimirsky@gmail.com
    name:
    username:
  normingtong@vmware.com:
    email: normingtong@vmware.com
    name:
    username:
  jason_livingood@comcast.com:
    email: jason_livingood@comcast.com
    name:
    username:
  flo@geekplace.eu:
    email: flo@geekplace.eu
    name:
    username:
  ekr@rtfm.com:
    email: ekr@rtfm.com
    name:
    username:
  johnl@taugh.com:
    email: johnl@taugh.com
    name:
    username:
  job@fastly.com:
    email: job@fastly.com
    name:
    username:
  stu.card@critical.com:
    email: stu.card@critical.com
    name:
    username:
  jennifer@painless-security.com:
    email: jennifer@painless-security.com
    name:
    username:
  cheshire@apple.com:
    email: cheshire@apple.com
    name:
    username:
  martin@gwerder.net:
    email: martin@gwerder.net
    name:
    username:
  dkg@fifthhorseman.net:
    email: dkg@fifthhorseman.net
    name:
    username:
  krathnayake@ietf.org:
    email: krathnayake@ietf.org
    name:
    username:
  tte+anima@cs.fau.de:
    email: tte+anima@cs.fau.de
    name:
    username:
  paul@nohats.ca:
    email: paul@nohats.ca
    name:
    username:
  mt@lowentropy.net:
    email: mt@lowentropy.net
    name:
    username:
  kesara@staff.ietf.org:
    email: kesara@staff.ietf.org
    name:
    username:
  alex_brotman@comcast.com:
    email: alex_brotman@comcast.com
    name:
    username:
  jbothun@concentricsky.com:
    email: jbothun@concentricsky.com
    name:
    username:
  Elwyn Davies:
    email: Elwyn Davies
    name:
    username:
  mrcullen42@gmail.com:
    email: mrcullen42@gmail.com
    name:
    username:
  mark@painless-security.com:
    email: mark@painless-security.com
    name:
    username:
  paul.hoffman@vpnc.org:
    email: paul.hoffman@vpnc.org
    name:
    username:
  barryleiba@computer.org:
    email: barryleiba@computer.org
    name:
    username:
  nico@cryptonector.com:
    email: nico@cryptonector.com
    name:
    username:
  fenner@fenron.net:
    email: fenner@fenron.net
    name:
    username:
  duerst@it.aoyama.ac.jp:
    email: duerst@it.aoyama.ac.jp
    name:
    username:
  dave@dericed.com:
    email: dave@dericed.com
    name:
    username:
  lars@eggert.org:
    email: lars@eggert.org
    name:
    username:
  stpeter@mozilla.com:
    email: stpeter@mozilla.com
    name:
    username:
  ietf@bobbriscoe.net:
    email: ietf@bobbriscoe.net
    name:
    username:
  evyncke@cisco.com:
    email: evyncke@cisco.com
    name:
    username:
  wiggins@concentricsky.com:
    email: wiggins@concentricsky.com
    name:
    username:
  dret@berkeley.edu:
    email: dret@berkeley.edu
    name:
    username:
milestones:
  '1.35':
    :name: '1.35'
    :due: 1270105200000000
    :completed: 1270052264000000
    :description: ''
  '1.36':
    :name: '1.36'
    :due: 1275375600000000
    :completed: 1301217258000000
    :description: ''
  '1.37':
    :name: '1.37'
    :due: 0
    :completed: 0
    :description: ''
labels:
  type:
    defect: type_defect
    task: type_task
    enhancement: type_enhancement
  component:
    Version 2 cli:
      name: "component_Version 2 cli"
      color: ff00ff
    vocabulary:
      name: "component_vocabulary"
      color: ff00ff
    xml2rfc.tcl:
      name: "component_xml2rfc.tcl"
      color: ff00ff
    Version 2 cli nroff:
      name: "component_Version 2 cli nroff"
      color: ff00ff
    Version 2 cli html:
      name: "component_Version 2 cli html"
      color: ff00ff
    Version 2 cli install:
      name: "component_Version 2 cli install"
      color: ff00ff
    Version 2 build:
      name: "component_Version 2 build"
      color: ff00ff
    Version 2 cli txt:
      name: "component_Version 2 cli txt"
      color: ff00ff
    Version 2 gui:
      name: "component_Version 2 gui"
      color: ff00ff
    Version_3_cli_txt:
      name: "component_Version_3_cli_txt"
      color: ff00ff
    Version_3_cli_html:
      name: "component_Version_3_cli_html"
      color: ff00ff
    v3 vocabulary:
      name: "component_v3 vocabulary"
      color: ff00ff
    preptool:
      name: "component_preptool"
      color: ff00ff
    idnits3:
      name: "component_idnits3"
      color: ff00ff
    rfclint:
      name: "component_rfclint"
      color: ff00ff
  resolution:
    fixed: resolution_fixed
    overtaken by events: resolution_overtaken by events
    invalid: resolution_invalid
    duplicate: resolution_duplicate
    wontfix: resolution_wontfix
    worksforme: resolution_worksforme
    obe: resolution_obe
  severity: {}
  priority:
    trivial:
      name: trivial
      color: 00ff00
    major:
      name: major
      color: f0f0f0
    minor:
      name: minor
      color: 0f0f0f
    medium:
      name: medium
      color: 00ffff
    critical:
      name: critical
      color: ffffff
    blocker:
      name: blocker
      color: f0000f
  tracstate:
    accepted:
      name: accepted
      color: abcdef
    assigned:
      name: assigned
      color: 12345f
    closed:
      name: closed
      color: f93a71
    new:
      name: new
      color: 55667f
    under_review:
      name: under_review
      color:
    waiting:
      name: waiting
      color:

ticket:
  attachments:
    url: https://abc.com/raw-attachment/ticket
    hashed: true

wiki:
  attachments:
    url: https://abc.com/raw-attachment/wiki
    hashed: true
