name: convert

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/install_reposurgeon.yml'
  schedule:
    - cron: '0 2 * * *'  # every day at 2:00

jobs:
  convert:
    name: convert
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        svn_repo:
          - ghostlinkd
          - datatracker
          - mailarch
          - mailreplay
          - postconfirm
          - postfind
          - vocabulary_design_team_2013_2017
          - xml2rfc
          - xml2rfc-bibxml
          - xml2rfc-website

    steps:
      - name: Setup Git
        run: |
          git config --global init.defaultBranch main
          git config --global user.name "ietf-ribose-ci"
          git config --global user.email "ietf-ribose-ci@users.noreply.github.com"

      - name: reposurgeon - Cache reposurgeon
        id: cache-reposurgeon
        uses: actions/cache@v2
        with:
          path: reposurgeon
          key: ${{ runner.os }}-${{ hashFiles('reposurgeon-cache-key') }}

      - name: reposurgeon - Clone and build reposurgeon
        if: steps.cache-reposurgeon.outputs.cache-hit != 'true'
        run: |
          git clone https://gitlab.com/esr/reposurgeon
          cd reposurgeon
          git checkout 2f5f83ec63da34beaf8293434b5e1627366dfa7c
          sed -i 's/apt-get install /apt-get install -y /' Makefile
          make fullinstall
          make all

      - name: reposurgeon - Install reposurgeon
        working-directory: reposurgeon
        run: |
          sudo make install

      - uses: actions/checkout@v2
        with:
          path: conversion

      - name: Add svn/ directory
        run: |
          mkdir -p svn git

      - name: Checkout trac-svn-db repo
        uses: actions/checkout@v2
        with:
          repository: ietf-ribose/trac-svn-db
          token: ${{ secrets.IETF_RIBOSE_CI_PAT }}
          path: trac-svn-db

      - name: Convert SVN to Git via reposurgeon
        if: ${{ matrix.svn_repo != 'xml2rfc-bibxml' && matrix.svn_repo != 'xml2rfc-website' && matrix.svn_repo != 'vocabulary_design_team_2013_2017' && matrix.svn_repo != 'datatracker' }}
        working-directory: conversion/${{ matrix.svn_repo }}
        env:
          TERM: xterm-256color
        run: |
          ln -s ../../trac-svn-db/svn/${{ matrix.svn_repo }} ${{ matrix.svn_repo }}-mirror
          make
          mv ${{ matrix.svn_repo }}-git ../../git/${{ matrix.svn_repo }}

      - name: Convert SVN to Git via reposurgeon
        if: ${{ matrix.svn_repo == 'xml2rfc-bibxml' || matrix.svn_repo == 'xml2rfc-website' || matrix.svn_repo == 'vocabulary_design_team_2013_2017' }}
        working-directory: conversion/${{ matrix.svn_repo }}
        env:
          TERM: xterm-256color
        run: |
          ln -s ../../trac-svn-db/svn/xml2rfc ${{ matrix.svn_repo }}-mirror
          make
          mv ${{ matrix.svn_repo }}-git ../../git/${{ matrix.svn_repo }}

      - name: Convert SVN to Git via reposurgeon
        if: ${{ matrix.svn_repo == 'datatracker' }}
        working-directory: conversion/${{ matrix.svn_repo }}
        env:
          TERM: xterm-256color
        run: |
          ln -s ../../trac-svn-db/svn/ietfdb ${{ matrix.svn_repo }}-mirror
          make
          mv ${{ matrix.svn_repo }}-git ../../git/${{ matrix.svn_repo }}

      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.IETF_RIBOSE_CI_SSH_PRIVATE }}

      - name: Checkout svn-git-maps repo
        uses: actions/checkout@v2
        with:
          repository: ietf-ribose/svn-git-maps
          token: ${{ secrets.IETF_RIBOSE_CI_PAT }}
          path: svn-git-maps

      - name: Tractive - Install tractive
        run: |
          sudo gem install tractive

      - name: Copy ${{ matrix.svn_repo }}.fo to svn-git-maps
        working-directory: svn-git-maps
        run: |
          git remote set-url origin \
            git@github.com:ietf-ribose/svn-git-maps.git
          cp ${GITHUB_WORKSPACE}/conversion/${{ matrix.svn_repo }}/${{ matrix.svn_repo }}.fo .

      - name: Convert ${{ matrix.svn_repo }}.fo to ${{ matrix.svn_repo }}-revmap.txt
        if: ${{ matrix.svn_repo != 'xml2rfc-bibxml' && matrix.svn_repo != 'xml2rfc-website' && matrix.svn_repo != 'vocabulary_design_team_2013_2017' && matrix.svn_repo != 'datatracker' }}
        working-directory: svn-git-maps
        run: |
          tractive generate revmap \
            --svn-url https://svn.ietf.org/svn/tools/${{ matrix.svn_repo }} \
            --git-local-repo-path ${GITHUB_WORKSPACE}/git/${{ matrix.svn_repo }} \
            --rev-timestamp-file ${{ matrix.svn_repo }}.fo \
            --revmap-output-file ./${{ matrix.svn_repo }}-revmap.txt

      - name: Convert ${{ matrix.svn_repo }}.fo to ${{ matrix.svn_repo }}-revmap.txt
        if: ${{ matrix.svn_repo == 'xml2rfc-bibxml' }}
        working-directory: svn-git-maps
        run: |
          tractive generate revmap \
            --svn-url https://svn.ietf.org/svn/tools/xml2rfc/website/rfcs \
            --git-local-repo-path ${GITHUB_WORKSPACE}/git/${{ matrix.svn_repo }} \
            --rev-timestamp-file ${{ matrix.svn_repo }}.fo \
            --revmap-output-file ./${{ matrix.svn_repo }}-revmap.txt

      - name: Convert ${{ matrix.svn_repo }}.fo to ${{ matrix.svn_repo }}-revmap.txt
        if: ${{ matrix.svn_repo == 'xml2rfc-website' }}
        working-directory: svn-git-maps
        run: |
          tractive generate revmap \
            --svn-url https://svn.ietf.org/svn/tools/xml2rfc/website \
            --git-local-repo-path ${GITHUB_WORKSPACE}/git/${{ matrix.svn_repo }} \
            --rev-timestamp-file ${{ matrix.svn_repo }}.fo \
            --revmap-output-file ./${{ matrix.svn_repo }}-revmap.txt

      - name: Convert ${{ matrix.svn_repo }}.fo to ${{ matrix.svn_repo }}-revmap.txt
        if: ${{ matrix.svn_repo == 'vocabulary_design_team_2013_2017' }}
        working-directory: svn-git-maps
        run: |
          tractive generate revmap \
            --svn-url https://svn.ietf.org/svn/tools/xml2rfc/vocabulary \
            --git-local-repo-path ${GITHUB_WORKSPACE}/git/${{ matrix.svn_repo }} \
            --rev-timestamp-file ${{ matrix.svn_repo }}.fo \
            --revmap-output-file ./${{ matrix.svn_repo }}-revmap.txt

      - name: Convert ${{ matrix.svn_repo }}.fo to ${{ matrix.svn_repo }}-revmap.txt
        if: ${{ matrix.svn_repo == 'datatracker' }}
        working-directory: svn-git-maps
        run: |
          tractive generate revmap \
            --svn-url https://svn.ietf.org/svn/tools/ietfdb \
            --git-local-repo-path ${GITHUB_WORKSPACE}/git/${{ matrix.svn_repo }} \
            --rev-timestamp-file ${{ matrix.svn_repo }}.fo \
            --revmap-output-file ./${{ matrix.svn_repo }}-revmap.txt

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Clone git-filter-repo
        run: |
          git clone \
            --branch changing_order_of_msg_update \
            --single-branch \
            git@github.com:riboseinc/git-filter-repo.git

      - name: Add references to commit SHA in commit messages
        working-directory: git/${{ matrix.svn_repo }}
        run: |
          python ${GITHUB_WORKSPACE}/git-filter-repo/git_filter_repo.py --force --order-by-date --message-callback '
            new_message = message
            revisions = re.findall(b"\[(\d+)\]", message)

            if revisions:
              file = open("../../svn-git-maps/${{ matrix.svn_repo }}-revmap.txt", "r")
              total_revisons = revisions.count
              ref_added = 0

              for line in file:
                rev, sha = line.split(" | ")
                sha = bytes(sha, "utf-8")
                rev = bytes(rev.replace("r", ""), "utf-8")
                if rev in revisions:
                  new_message = new_message + b"\nNote: SVN reference [" + rev + b"] has been migrated to Git commit " + sha
                  ref_added += 1

                if total_revisons == ref_added:
                  break

              file.close()

            return new_message'

      - name: Update ${{ matrix.svn_repo }}-revmap.txt
        if: ${{ matrix.svn_repo != 'xml2rfc-bibxml' && matrix.svn_repo != 'xml2rfc-website' && matrix.svn_repo != 'vocabulary_design_team_2013_2017' && matrix.svn_repo != 'datatracker' }}
        working-directory: svn-git-maps
        run: |
          tractive generate revmap \
            --svn-url https://svn.ietf.org/svn/tools/${{ matrix.svn_repo }} \
            --git-local-repo-path ${GITHUB_WORKSPACE}/git/${{ matrix.svn_repo }} \
            --rev-timestamp-file ${{ matrix.svn_repo }}.fo \
            --revmap-output-file ./${{ matrix.svn_repo }}-revmap.txt

      - name: Update ${{ matrix.svn_repo }}-revmap.txt
        if: ${{ matrix.svn_repo == 'xml2rfc-bibxml' }}
        working-directory: svn-git-maps
        run: |
          tractive generate revmap \
            --svn-url https://svn.ietf.org/svn/tools/xml2rfc/website/rfcs \
            --git-local-repo-path ${GITHUB_WORKSPACE}/git/${{ matrix.svn_repo }} \
            --rev-timestamp-file ${{ matrix.svn_repo }}.fo \
            --revmap-output-file ./${{ matrix.svn_repo }}-revmap.txt

      - name: Update ${{ matrix.svn_repo }}-revmap.txt
        if: ${{ matrix.svn_repo == 'xml2rfc-website' }}
        working-directory: svn-git-maps
        run: |
          tractive generate revmap \
            --svn-url https://svn.ietf.org/svn/tools/xml2rfc/website \
            --git-local-repo-path ${GITHUB_WORKSPACE}/git/${{ matrix.svn_repo }} \
            --rev-timestamp-file ${{ matrix.svn_repo }}.fo \
            --revmap-output-file ./${{ matrix.svn_repo }}-revmap.txt

      - name: Update ${{ matrix.svn_repo }}-revmap.txt
        if: ${{ matrix.svn_repo == 'vocabulary_design_team_2013_2017' }}
        working-directory: svn-git-maps
        run: |
          tractive generate revmap \
            --svn-url https://svn.ietf.org/svn/tools/xml2rfc/vocabulary \
            --git-local-repo-path ${GITHUB_WORKSPACE}/git/${{ matrix.svn_repo }} \
            --rev-timestamp-file ${{ matrix.svn_repo }}.fo \
            --revmap-output-file ./${{ matrix.svn_repo }}-revmap.txt

      - name: Update ${{ matrix.svn_repo }}-revmap.txt
        if: ${{ matrix.svn_repo == 'datatracker' }}
        working-directory: svn-git-maps
        run: |
          tractive generate revmap \
            --svn-url https://svn.ietf.org/svn/tools/ietfdb \
            --git-local-repo-path ${GITHUB_WORKSPACE}/git/${{ matrix.svn_repo }} \
            --rev-timestamp-file ${{ matrix.svn_repo }}.fo \
            --revmap-output-file ./${{ matrix.svn_repo }}-revmap.txt

      - name: Add GitHub remote to ${{ matrix.svn_repo }} repo
        working-directory: git/${{ matrix.svn_repo }}
        run: |
          git remote add origin \
            git@github.com:ietf-ribose/${{ matrix.svn_repo }}.git

      - name: Checkout to main branch
        working-directory: git/${{ matrix.svn_repo }}
        run: |
          git checkout main

      - name: List git branches
        # if: steps.git_status.outputs.STATUS != ''
        working-directory: git/${{ matrix.svn_repo }}
        run: |
          git branch

      - name: List git tags
        # if: steps.git_status.outputs.STATUS != ''
        working-directory: git/${{ matrix.svn_repo }}
        run: |
          git tag

      - name: Git push to GitHub ${{ matrix.svn_repo }}
        # if: steps.git_status.outputs.STATUS != ''
        working-directory: git/${{ matrix.svn_repo }}
        run: |
          max=$(git log --oneline|wc -l); \
          for i in $(seq $max -500 1); do \
            echo $i; g=$(git log --reverse --oneline --skip $i -n1|perl -alne'print $F[0]'); \
            git push origin $g:refs/heads/gitconvert -f; \
          done

          for x in $(git branch | tr -ds '*' '' | paste -d " " - - - - - - - - - - | tr -s ' ' '#'); do \
            y="${x//#/ }"; \
            echo $y; \
            git push origin -f $y; \
          done

          for x in $(git tag | tr -ds '*' '' | paste -d " " - - - - - - - - - - | tr -s ' ' '#'); do \
            y="${x//#/ }"; \
            echo $y; \
            git push origin -f $y; \
          done

          git push origin :refs/heads/gitconvert -f

      - name: Skip push to svn-git-maps if no changes
        id: git_status
        working-directory: svn-git-maps
        run: |
          echo ::set-output name=STATUS::$(git status --porcelain | tr -d [:space:])

      - name: Add and push changes to svn-git-maps
        if: steps.git_status.outputs.STATUS != ''
        working-directory: svn-git-maps
        run: |
          git add ${{ matrix.svn_repo }}.fo ${{ matrix.svn_repo }}-revmap.txt
          git commit -m 'Update ${{ matrix.svn_repo }} mapping'
          timeout 30s bash -c 'until git pull --rebase && git push; do sleep 3; done'
