name: install_reposurgeon

on:
  push:
    branches: [ main ]

jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git
        run: |
          git config --global user.name "ietf-ribose-ci"
          git config --global user.email "ietf-ribose-ci@users.noreply.github.com"

      - name: Install hg-git-fast-import
        uses: actions-rs/install@v0.1
        with:
          crate: hg-git-fast-import
          version: latest
          use-tool-cache: true

      - name: Install gawk
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gawk

      - name: Cache reposurgeon
        id: cache-reposurgeon
        uses: actions/cache@v2
        with:
          path: reposurgeon
          key: ${{ runner.os }}-${{ hashFiles('reposurgeon-cache-key') }}

      - name: Clone and build reposurgeon
        if: steps.cache-reposurgeon.outputs.cache-hit != 'true'
        run: |
          git clone https://gitlab.com/esr/reposurgeon
          cd reposurgeon
          sed -i 's/sudo apt-get install asciidoctor awk/sudo apt-get install asciidoctor/' Makefile
          sed -i 's/hg-git-fast-import //' Makefile
          sed -i 's/apt-get install /apt-get install -y /' Makefile
          make fullinstall
          make all

      - name: Install reposurgeon
        working-directory: reposurgeon
        run: |
          sudo make install
