name: install_reposurgeon

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/convert.yml'

jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git
        run: |
          git config --global user.name "ietf-ribose-ci"
          git config --global user.email "ietf-ribose-ci@users.noreply.github.com"

      - name: Cache reposurgeon
        id: cache-reposurgeon
        uses: actions/cache@v2
        with:
          path: reposurgeon
          key: ${{ runner.os }}-${{ hashFiles('reposurgeon-cache-key') }}

      - name: Clone and build reposurgeon
        if: steps.cache-reposurgeon.outputs.cache-hit != 'true'
        run: |
          git clone https://gitlab.com/esr/reposurgeon
          cd reposurgeon
          git checkout 2f5f83ec63da34beaf8293434b5e1627366dfa7c
          sed -i 's/apt-get install /apt-get install -y /' Makefile
          make fullinstall
          make all

      - name: Install reposurgeon
        working-directory: reposurgeon
        run: |
          sudo make install
