name: migrate_tickets

on:
  push:
    branches: [ testting_credentials ]
  workflow_run:
    workflows: [convert]
    types:
      - completed

jobs:
  migrate_tickets:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        git_repo:
          - tsvwg
          - emailcore
          - dmarc

    steps:
      - name: Tractive - Install tractive
        run: |
          sudo gem install tractive

      - uses: actions/checkout@v2
        with:
          path: conversion

      - name: Checkout trac-svn-db repo
        uses: actions/checkout@v2
        with:
          repository: ietf-ribose/trac-svn-db
          token: ${{ secrets.IETF_RIBOSE_CI_PAT }}
          path: trac-svn-db

      - name: Checkout svn-git-maps repo
        uses: actions/checkout@v2
        with:
          repository: ietf-ribose/svn-git-maps
          token: ${{ secrets.IETF_RIBOSE_CI_PAT }}
          path: svn-git-maps
          
      - name: Test token
        run: |
          url -H "Authorization: bearer ${{ secrets.IETF_SVN_BOT_PAT_TOKEN }}" -X POST -d "{\"query\":\"query IntrospectionQuery {\\n  __schema {\\n    queryType {\\n      name\\n    }\\n    mutationType {\\n      name\\n    }\\n    subscriptionType {\\n      name\\n    }\\n    types {\\n      ...FullType\\n    }\\n    directives {\\n      name\\n      description\\n      locations\\n      args {\\n        ...InputValue\\n      }\\n    }\\n  }\\n}\\n\\nfragment FullType on __Type {\\n  kind\\n  name\\n  description\\n  fields(includeDeprecated: true) {\\n    name\\n    description\\n    args {\\n      ...InputValue\\n    }\\n    type {\\n      ...TypeRef\\n    }\\n    isDeprecated\\n    deprecationReason\\n  }\\n  inputFields {\\n    ...InputValue\\n  }\\n  interfaces {\\n    ...TypeRef\\n  }\\n  enumValues(includeDeprecated: true) {\\n    name\\n    description\\n    isDeprecated\\n    deprecationReason\\n  }\\n  possibleTypes {\\n    ...TypeRef\\n  }\\n}\\n\\nfragment InputValue on __InputValue {\\n  name\\n  description\\n  type {\\n    ...TypeRef\\n  }\\n  defaultValue\\n}\\n\\nfragment TypeRef on __Type {\\n  kind\\n  name\\n  ofType {\\n    kind\\n    name\\n    ofType {\\n      kind\\n      name\\n      ofType {\\n        kind\\n        name\\n        ofType {\\n          kind\\n          name\\n          ofType {\\n            kind\\n            name\\n            ofType {\\n              kind\\n              name\\n              ofType {\\n                kind\\n                name\\n              }\\n            }\\n          }\\n        }\\n      }\\n    }\\n  }\\n}\",\"operationName\":\"IntrospectionQuery\"}" https://api.github.com/graphql

      - name: Migrate Tickets
        run: |
          tractive -c "./conversion/tractive_configurations/${{ matrix.git_repo }}.config.yaml" --git-token "${{ secrets.IETF_SVN_BOT_PAT_TOKEN }}" -M
