name: migrate_tickets

on:
  workflow_run:
    workflows: [convert]
    types:
      - completed

jobs:
  migrate_tickets:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        git_repo:
          - xml2rfc
          - datatracker
          - mailarch

    steps:
      - name: Tractive - Install tractive
        run: |
          sudo gem install tractive

      - uses: actions/checkout@v2
        with:
          path: conversion

      - name: Checkout trac-svn-db repo
        uses: actions/checkout@v2
        with:
          repository: ietf-ribose/trac-svn-db
          token: ${{ secrets.IETF_RIBOSE_CI_PAT }}
          path: trac-svn-db

      - name: Checkout svn-git-maps repo
        uses: actions/checkout@v2
        with:
          repository: ietf-ribose/svn-git-maps
          token: ${{ secrets.IETF_RIBOSE_CI_PAT }}
          path: svn-git-maps

      - name: Migrate Tickets
        if: ${{ matrix.git_repo != 'datatracker' && matrix.git_repo != 'mailarch' }}
        run: |
          tractive -M \
            -c "./conversion/tractive_configurations/${{ matrix.git_repo }}.config.yaml" \
            --git-token "${{ secrets.IETF_SVN_BOT_PAT_TOKEN }}"

      - name: Migrate Tickets
        if: ${{ matrix.git_repo == 'datatracker' }}
        run: |
          tractive -M --include-null --filter \
            --column-name "component" \
            --operator "NOT LIKE" \
            --column-value "MailArchive:%"
            -c "./conversion/tractive_configurations/${{ matrix.git_repo }}.config.yaml" \
            --git-token "${{ secrets.IETF_SVN_BOT_PAT_TOKEN }}"

      - name: Migrate Tickets
        if: ${{ matrix.git_repo == 'mailarch' }}
        run: |
          tractive -M --filter \
            --column-name "component" \
            --operator "NOT LIKE" \
            --column-value "MailArchive:%"
            -c "./conversion/tractive_configurations/${{ matrix.git_repo }}.config.yaml" \
            --git-token "${{ secrets.IETF_SVN_BOT_PAT_TOKEN }}"
